### ISSUE TITLE
Broken link of Susy for grids 

### ISSUE THREAD

**Issue by vbaimas** [lucijanblagonic/wceu-2018#51]
Hello @lucijanblagonic,

First of all, I want thank you for this useful guide. It will help all the community to create easily and fast the theme for WordCamp.

As  I was reading the **Interesting Bits** section, I realized that the **Uses [Susy](https://github.com/lucijanblagonic/wceu-2018/blob/master/susy.oddbird.net) for grids** have a broken link. 

Please, can you update the link and replace with the new one?

Best Regards,
Vasilis.

**Comment by lucijanblagonic** [comment]
Thanks @vbaimas for the info! Fixed the link!
